# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------
name: Santosh Kumar Radha
email: srr70@case.edu
description: > # this means to ignore newlines until "url:"
  Personal webpage
footer_text: >

url: https://santoshkumarradha.github.io
baseurl:  # the subpath of your site, e.g. /blog/
last_updated: # leave blank if you don't want to display last updated

# -----------------------------------------------------------------------------
# Social integration
# -----------------------------------------------------------------------------
github_username: santoshkumarradha
twitter_username: # put your twitter username
linkedin_username: santoshr93
scholar_authorid: # put your google scholar author id
contact_note: >
  Easist to reach me is via email - srr70@case.edu

# -----------------------------------------------------------------------------
# Blog
# -----------------------------------------------------------------------------
blog_name: Condensed diaries
blog_description: Thoughts, ideas and comments of an intelectually discomforted mind ranging from topics in condensed matter physics to carnatic music

# Pagination
paginate: 20
permalink: /blog/:year/:title/
paginate_path: /blog/page:num/

text:
  pagination:
    newer: 'Newer'
    older: 'Older'

# Comments
disqus_shortname: santy # put your disqus shortname

# Optional features
show_social_icons:  false
enable_anchorjs:    false
enable_katex:       true

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------
collections:
  news:
    defaults:
      layout: post
    output: true
    permalink: /news/:path/
  projects:
    output: true
    permalink: /projects/:path/

news_limit: 5

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

# Build settings
markdown: kramdown
highlighter: pygments

# Includes
include: ['_pages']

# Gems
gems:
    - jekyll-paginate
    - jekyll/scholar
    - jemoji

# Jekyll-Scholar
scholar:

  last_name: Kumar

  style: apa
  locale: en

  sort_by: year
  order: descending

  source: /_bibliography/
  bibliography: papers.bib
  bibliography_template: bib

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

# -----------------------------------------------------------------------------
# Other settings
# -----------------------------------------------------------------------------
jquery_version: "1.12.4"
katex_version: "0.7.1"
anchorjs_version: "3.2.2"
plugins:
  - jekyll-sitemap
